name: Device Request Comment

on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    if: github.event.label.name == 'device-request'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add helpful comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for requesting support for a new headset!

            To implement support for a specific headset, we need to reverse-engineer and test on that device. **Only people who own the headset can implement support for it.**

            ### Want to help?

            1. Check our [Development Wiki](https://github.com/Sapd/HeadsetControl/wiki/Development) to get started
            2. Use Wireshark to capture USB traffic from the official software
            3. Post your findings (screenshots, data) here - we're happy to help!

            See [ADDING_A_DEVICE.md](https://github.com/Sapd/HeadsetControl/blob/master/docs/ADDING_A_DEVICE.md) for detailed instructions.
